-- Book 5 Seed Data

-- Insert Book
INSERT INTO books (id, name, level, description) VALUES (5, 'Book 5', 'Intermediate', 'Intermediate level content');

-- Insert Units
INSERT INTO units (book_id, name, `order`) VALUES (5, 'Friends, Family & Relationships', 1);
INSERT INTO units (book_id, name, `order`) VALUES (5, 'Shapes and Colors', 2);
INSERT INTO units (book_id, name, `order`) VALUES (5, 'Crime and Punishment', 3);
INSERT INTO units (book_id, name, `order`) VALUES (5, 'Permission and Prohibition', 4);
INSERT INTO units (book_id, name, `order`) VALUES (5, 'Arguing and Making up', 5);
INSERT INTO units (book_id, name, `order`) VALUES (5, 'Storytelling', 6);
INSERT INTO units (book_id, name, `order`) VALUES (5, 'Advanced Topics', 7);

-- Insert Lessons
INSERT INTO lessons (book_id, unit_id, number, title) VALUES (5, 1, 1, 'Friends and Acquaintances');
INSERT INTO lessons (book_id, unit_id, number, title) VALUES (5, 1, 2, 'Friends and Acquaintances');
INSERT INTO lessons (book_id, unit_id, number, title) VALUES (5, 1, 3, 'Family and Relationship');
INSERT INTO lessons (book_id, unit_id, number, title) VALUES (5, 1, 4, 'Family and Relationship');
INSERT INTO lessons (book_id, unit_id, number, title) VALUES (5, 2, 5, 'Shapes and Colors');
INSERT INTO lessons (book_id, unit_id, number, title) VALUES (5, 2, 6, 'Shapes and Colors');
INSERT INTO lessons (book_id, unit_id, number, title) VALUES (5, 3, 7, 'Crime and Punishment');
INSERT INTO lessons (book_id, unit_id, number, title) VALUES (5, 3, 8, 'Crime and Punishment');
INSERT INTO lessons (book_id, unit_id, number, title) VALUES (5, 4, 9, 'Permission and Prohibition');
INSERT INTO lessons (book_id, unit_id, number, title) VALUES (5, 4, 10, 'Permission and Prohibition');
INSERT INTO lessons (book_id, unit_id, number, title) VALUES (5, 5, 11, 'Arguing and Making up');
INSERT INTO lessons (book_id, unit_id, number, title) VALUES (5, 5, 12, 'Arguing and Making up');
INSERT INTO lessons (book_id, unit_id, number, title) VALUES (5, 6, 13, 'Storytelling');
INSERT INTO lessons (book_id, unit_id, number, title) VALUES (5, 6, 14, 'Storytelling');
INSERT INTO lessons (book_id, unit_id, number, title) VALUES (5, 7, 15, 'Book 5');
INSERT INTO lessons (book_id, unit_id, number, title) VALUES (5, 7, 16, 'Book 5');
INSERT INTO lessons (book_id, unit_id, number, title) VALUES (5, 7, 17, 'Book 5');
INSERT INTO lessons (book_id, unit_id, number, title) VALUES (5, 7, 18, 'Book 5');
INSERT INTO lessons (book_id, unit_id, number, title) VALUES (5, 7, 19, 'Book 5');
INSERT INTO lessons (book_id, unit_id, number, title) VALUES (5, 7, 20, 'Book 5');
INSERT INTO lessons (book_id, unit_id, number, title) VALUES (5, 7, 21, 'Book 5');
INSERT INTO lessons (book_id, unit_id, number, title) VALUES (5, 7, 22, 'Book 5');
INSERT INTO lessons (book_id, unit_id, number, title) VALUES (5, 7, 23, 'Book 5');
INSERT INTO lessons (book_id, unit_id, number, title) VALUES (5, 7, 24, 'Book 5');
INSERT INTO lessons (book_id, unit_id, number, title) VALUES (5, 7, 25, 'Book 5');
INSERT INTO lessons (book_id, unit_id, number, title) VALUES (5, 7, 26, 'Book 5');
INSERT INTO lessons (book_id, unit_id, number, title) VALUES (5, 7, 27, 'Book 5');
INSERT INTO lessons (book_id, unit_id, number, title) VALUES (5, 7, 28, 'Book 5');
INSERT INTO lessons (book_id, unit_id, number, title) VALUES (5, 7, 29, 'Book 5');
INSERT INTO lessons (book_id, unit_id, number, title) VALUES (5, 7, 30, 'Book 5');

-- Insert Vocabulary
INSERT INTO vocabulary (lesson_id, word, type) VALUES (1, 'MEAN', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (1, 'TO GET TO KNOW', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (1, 'VAIN', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (1, 'STRAIGHTFORWARD', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (1, 'TO KEEP IT TO YOURSELF', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (1, 'TO CONVINCE / CONVINCED / CONVINCED', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (1, 'GRATEFUL WELL', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (1, 'ENVIOUS / ENVY', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (1, 'CHILDISH', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (1, 'TO SPEAK (YOUR) MIND', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (1, 'CONFIDENT', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (3, 'TO BELONG / BELONGED / BELONGED', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (3, 'TO BE HEADING (FOR / TO)', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (3, 'TO BE FULL OF (YOURSELF)', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (3, 'TO STARE / STARED / STARED', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (3, 'BIG HEADED', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (3, 'FAITHFUL', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (3, 'TO PASS AWAY', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (3, 'NO', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (3, 'GRUMPY', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (3, 'PREJUDICE', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (5, 'TO DRAW THE LINE', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (5, 'OUT OF THE BLUE', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (5, 'TO COLOR / COLORED / COLORED', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (5, 'RED TAPE', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (5, 'BUMPY', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (5, 'TRIANGULAR / SHAPE', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (5, 'TO STRAIGHTEN UP TO JOT DOWN', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (5, 'TO DRAW NEAR', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (5, 'DEPTH / LENGTH / WIDTH', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (5, 'ARCH', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (5, 'BOUNDARY', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (5, 'SHAPE', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (5, 'LINE', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (6, 'ACTIVITY', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (7, 'TO RAT ON (SOMEBODY)', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (7, 'JAIL', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (7, 'SELF', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (7, 'TO BE CONVICTED OF', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (7, 'TO GET WORSE AND WORSE', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (7, 'TO SET (SOMEBODY) FREE', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (7, 'DEATH SENTENCE / LIFE SENTENCE', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (7, 'TO PRESS CHARGES AGAINST', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (7, 'TO SUE / SUED / SUED', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (7, 'ATTORNEY', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (7, 'TO DEFEND / DEFENDED / DEFENDED', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (7, 'TRAP', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (7, 'KIDNAP', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (9, 'RESTRICTION', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (9, 'TO LIMIT YOURSELF TO', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (9, 'BY THE BOOK', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (9, 'LAW', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (9, 'TO ALLOW / ALLOWED / ALLOWED', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (9, 'TO LIMIT / LIMITED / LIMITED', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (9, 'WHAT GOOD IS (IT)', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (9, 'CURFEW', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (9, 'LIMIT', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (9, 'A', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (11, 'TO SHOUT / SHOUTED / SHOUTED', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (11, 'NOWHERE', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (11, 'ARGUMENT', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (11, 'TO DISAGREE / DISAGREED / DISAGREED', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (11, 'TO ARGUE / ARGUED / ARGUED', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (11, 'TO INTERFERE / INTERFERED / INTERFERED', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (11, 'TO PICK A FIGHT', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (11, 'TO CRITICIZE / CRITICIZED / CRITICIZED', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (11, 'TO TELL (SOMEBODY) TO (THEIR) FACE', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (11, 'TO', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (11, 'TOLERANT', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (11, 'TO DROP THE SUBJECT', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (11, '(NO) HARD FEELINGS', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (11, 'INTOLERABLE', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (11, 'TO MAKE UP (WITH)', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (11, 'TO DARE / DARED / DARED', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (13, 'TALE', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (13, 'ALTOGETHER', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (13, 'TO MAKE UP', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (13, 'WE USE THE (MORE / ETC', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (13, 'BETTER THAN EVER', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (13, 'REMARK', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (13, 'EXCEPT', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (13, 'TO', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (13, 'AT', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (15, 'OVERTIME HELPING YOU', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (19, 'TO', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (23, 'PILES (OF)', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (23, 'TO NIBBLE / NIBBLED / NIBBLED', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (23, 'DENT', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (23, 'STANDARD', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (23, 'TO SEW UP', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (23, 'STANDARD OF LIVING', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (24, 'USDA', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (27, 'PACKED HELPING YOU', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (27, 'BORED HELPING YOU', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (27, 'AGITATED', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (27, 'SEAT HELPING YOU', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (28, 'ACTIVITY', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (29, 'THE', 'vocabulary');
INSERT INTO vocabulary (lesson_id, word, type) VALUES (29, 'PROGRESS', 'vocabulary');

-- Insert Chunks
INSERT INTO chunks (lesson_id, expression, type) VALUES (1, 'confident about', 'chunk');
INSERT INTO chunks (lesson_id, expression, type) VALUES (1, 'by sight', 'chunk');
INSERT INTO chunks (lesson_id, expression, type) VALUES (1, 'envious of', 'chunk');
INSERT INTO chunks (lesson_id, expression, type) VALUES (1, 'get acquainted', 'chunk');
INSERT INTO chunks (lesson_id, expression, type) VALUES (1, 'envy of', 'chunk');
INSERT INTO chunks (lesson_id, expression, type) VALUES (1, 'get to know', 'chunk');
INSERT INTO chunks (lesson_id, expression, type) VALUES (1, 'confidence in', 'chunk');
INSERT INTO chunks (lesson_id, expression, type) VALUES (1, 'keep it to', 'chunk');
INSERT INTO chunks (lesson_id, expression, type) VALUES (1, 'speak your mind', 'chunk');
INSERT INTO chunks (lesson_id, expression, type) VALUES (1, 'at times', 'chunk');
INSERT INTO chunks (lesson_id, expression, type) VALUES (1, 'team player', 'chunk');
INSERT INTO chunks (lesson_id, expression, type) VALUES (3, 'unfaithful to', 'chunk');
INSERT INTO chunks (lesson_id, expression, type) VALUES (3, 'no matter', 'chunk');
INSERT INTO chunks (lesson_id, expression, type) VALUES (3, 'headed to', 'chunk');
INSERT INTO chunks (lesson_id, expression, type) VALUES (3, 'faithful to', 'chunk');
INSERT INTO chunks (lesson_id, expression, type) VALUES (3, 'full of', 'chunk');
INSERT INTO chunks (lesson_id, expression, type) VALUES (3, 'pass away', 'chunk');
INSERT INTO chunks (lesson_id, expression, type) VALUES (3, 'belong to', 'chunk');
INSERT INTO chunks (lesson_id, expression, type) VALUES (3, 'belongs to', 'chunk');
INSERT INTO chunks (lesson_id, expression, type) VALUES (3, 'prejudiced against', 'chunk');
INSERT INTO chunks (lesson_id, expression, type) VALUES (3, 'prejudice against', 'chunk');
INSERT INTO chunks (lesson_id, expression, type) VALUES (3, 'stare at', 'chunk');
INSERT INTO chunks (lesson_id, expression, type) VALUES (3, 'heading for', 'chunk');
INSERT INTO chunks (lesson_id, expression, type) VALUES (4, 'unfaithful to', 'chunk');
INSERT INTO chunks (lesson_id, expression, type) VALUES (4, 'faithful to', 'chunk');
