export const ENV = {
  appId: process.env.VITE_APP_ID ?? "influx-tutor",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  sponteLogin: process.env.SPONTE_LOGIN ?? "",
  spontePassword: process.env.SPONTE_PASSWORD ?? "",
  geminiApiKey: process.env.GEMINI_API_KEY ?? "",
  centralDatabaseUrl: process.env.CENTRAL_DATABASE_URL ?? "",
  openaiApiKey: process.env.OPENAI_API_KEY ?? "",
  elevenlabsApiKey: process.env.ELEVENLABS_API_KEY ?? "",
  googleCloudTtsApiKey: process.env.GOOGLE_CLOUD_TTS_API_KEY ?? "",
};
