// Seed: Badge Definitions for Ellie's Stamp System
// Each badge has PT-BR and EN descriptions, Ellie's congratulation message, and influxcoins reward

export const badgeDefinitions = [
  // ===== WELCOME BADGES =====
  {
    slug: "welcome_explorer",
    name: "Explorador Iniciante",
    nameEn: "Welcome Explorer",
    description: "Primeiro acesso ao sistema! Ellie te deu as boas-vindas.",
    descriptionEn: "First login to the system! Ellie welcomed you.",
    ellieMessage: "Welcome aboard! 🎉 Que bom ter você aqui! Eu sou a Ellie e vou te acompanhar nessa jornada. Ready to start?",
    ellieMessageEn: "Welcome aboard! 🎉 So glad to have you here! I'm Ellie and I'll be with you on this journey. Ready to start?",
    category: "welcome",
    icon: "🌟",
    color: "#F59E0B",
    requirement: JSON.stringify({ type: "first_login" }),
    influxcoinsReward: 10,
    sortOrder: 1
  },
  {
    slug: "passport_activated",
    name: "Passaporte Ativado",
    nameEn: "Passport Activated",
    description: "Escaneou o QR Code do passaporte pela primeira vez!",
    descriptionEn: "Scanned the passport QR Code for the first time!",
    ellieMessage: "Your passport is now active! ✈️ Agora você tem seu passaporte digital. Cada selo que você ganhar vai aparecer aqui. Let's collect them all!",
    ellieMessageEn: "Your passport is now active! ✈️ Now you have your digital passport. Every stamp you earn will show up here. Let's collect them all!",
    category: "welcome",
    icon: "✈️",
    color: "#3B82F6",
    requirement: JSON.stringify({ type: "passport_scan", count: 1 }),
    influxcoinsReward: 15,
    sortOrder: 2
  },
  {
    slug: "profile_complete",
    name: "Perfil Completo",
    nameEn: "Profile Complete",
    description: "Completou todas as informações do perfil!",
    descriptionEn: "Completed all profile information!",
    ellieMessage: "Awesome! 📋 Agora eu conheço você melhor e posso personalizar sua experiência. The more I know, the better I can help!",
    ellieMessageEn: "Awesome! 📋 Now I know you better and can personalize your experience. The more I know, the better I can help!",
    category: "welcome",
    icon: "📋",
    color: "#10B981",
    requirement: JSON.stringify({ type: "profile_complete" }),
    influxcoinsReward: 10,
    sortOrder: 3
  },

  // ===== EXERCISE BADGES =====
  {
    slug: "first_exercise",
    name: "Primeiro Exercício",
    nameEn: "First Exercise",
    description: "Completou o primeiro exercício extra!",
    descriptionEn: "Completed the first extra exercise!",
    ellieMessage: "You did it! 💪 Seu primeiro exercício extra está completo. That's the spirit! Keep going!",
    ellieMessageEn: "You did it! 💪 Your first extra exercise is complete. That's the spirit! Keep going!",
    category: "exercise",
    icon: "💪",
    color: "#8B5CF6",
    requirement: JSON.stringify({ type: "exercises_completed", count: 1 }),
    influxcoinsReward: 5,
    sortOrder: 10
  },
  {
    slug: "exercise_5",
    name: "Praticante Dedicado",
    nameEn: "Dedicated Practitioner",
    description: "Completou 5 exercícios extras!",
    descriptionEn: "Completed 5 extra exercises!",
    ellieMessage: "Five down! 🎯 Você está criando um hábito incrível. Practice makes perfect, right?",
    ellieMessageEn: "Five down! 🎯 You're building an amazing habit. Practice makes perfect, right?",
    category: "exercise",
    icon: "🎯",
    color: "#8B5CF6",
    requirement: JSON.stringify({ type: "exercises_completed", count: 5 }),
    influxcoinsReward: 15,
    sortOrder: 11
  },
  {
    slug: "exercise_10",
    name: "Mestre dos Exercícios",
    nameEn: "Exercise Master",
    description: "Completou 10 exercícios extras!",
    descriptionEn: "Completed 10 extra exercises!",
    ellieMessage: "Ten exercises! 🏆 You're on fire! Sua dedicação é inspiradora. I'm so proud of you!",
    ellieMessageEn: "Ten exercises! 🏆 You're on fire! Your dedication is inspiring. I'm so proud of you!",
    category: "exercise",
    icon: "🏆",
    color: "#6D28D9",
    requirement: JSON.stringify({ type: "exercises_completed", count: 10 }),
    influxcoinsReward: 30,
    sortOrder: 12
  },
  {
    slug: "exercise_25",
    name: "Campeão de Exercícios",
    nameEn: "Exercise Champion",
    description: "Completou 25 exercícios extras!",
    descriptionEn: "Completed 25 extra exercises!",
    ellieMessage: "Twenty-five! 🌟 You're absolutely crushing it! Você é um exemplo para todos os alunos!",
    ellieMessageEn: "Twenty-five! 🌟 You're absolutely crushing it! You're a role model for all students!",
    category: "exercise",
    icon: "👑",
    color: "#4C1D95",
    requirement: JSON.stringify({ type: "exercises_completed", count: 25 }),
    influxcoinsReward: 50,
    sortOrder: 13
  },

  // ===== STREAK BADGES =====
  {
    slug: "streak_3",
    name: "Sequência de 3 Dias",
    nameEn: "3-Day Streak",
    description: "Praticou por 3 dias seguidos!",
    descriptionEn: "Practiced for 3 consecutive days!",
    ellieMessage: "Three days in a row! 🔥 Consistency is key! Manter o ritmo é o segredo do sucesso.",
    ellieMessageEn: "Three days in a row! 🔥 Consistency is key! Keeping the rhythm is the secret to success.",
    category: "streak",
    icon: "🔥",
    color: "#EF4444",
    requirement: JSON.stringify({ type: "streak_days", count: 3 }),
    influxcoinsReward: 10,
    sortOrder: 20
  },
  {
    slug: "streak_7",
    name: "Sequência Semanal",
    nameEn: "Weekly Streak",
    description: "Praticou por 7 dias seguidos!",
    descriptionEn: "Practiced for 7 consecutive days!",
    ellieMessage: "A whole week! 🗓️ That's amazing dedication! Uma semana inteira sem parar. You're unstoppable!",
    ellieMessageEn: "A whole week! 🗓️ That's amazing dedication! A whole week without stopping. You're unstoppable!",
    category: "streak",
    icon: "🗓️",
    color: "#DC2626",
    requirement: JSON.stringify({ type: "streak_days", count: 7 }),
    influxcoinsReward: 25,
    sortOrder: 21
  },
  {
    slug: "streak_30",
    name: "Mestre da Consistência",
    nameEn: "Consistency Master",
    description: "Praticou por 30 dias seguidos!",
    descriptionEn: "Practiced for 30 consecutive days!",
    ellieMessage: "THIRTY DAYS! 🏅 You're a legend! Um mês inteiro de prática. This is what champions are made of!",
    ellieMessageEn: "THIRTY DAYS! 🏅 You're a legend! A whole month of practice. This is what champions are made of!",
    category: "streak",
    icon: "🏅",
    color: "#B91C1C",
    requirement: JSON.stringify({ type: "streak_days", count: 30 }),
    influxcoinsReward: 100,
    sortOrder: 22
  },

  // ===== VOCABULARY BADGES =====
  {
    slug: "vocab_explorer",
    name: "Explorador de Vocabulário",
    nameEn: "Vocabulary Explorer",
    description: "Aprendeu 20 novas palavras/expressões!",
    descriptionEn: "Learned 20 new words/expressions!",
    ellieMessage: "20 new words! 📚 Your vocabulary is growing fast! Cada palavra nova é uma porta que se abre.",
    ellieMessageEn: "20 new words! 📚 Your vocabulary is growing fast! Every new word is a door that opens.",
    category: "vocabulary",
    icon: "📚",
    color: "#059669",
    requirement: JSON.stringify({ type: "vocabulary_learned", count: 20 }),
    influxcoinsReward: 15,
    sortOrder: 30
  },
  {
    slug: "vocab_master",
    name: "Mestre do Vocabulário",
    nameEn: "Vocabulary Master",
    description: "Aprendeu 50 novas palavras/expressões!",
    descriptionEn: "Learned 50 new words/expressions!",
    ellieMessage: "Fifty words! 🧠 Your brain is a sponge! Você está absorvendo tudo. Impressive!",
    ellieMessageEn: "Fifty words! 🧠 Your brain is a sponge! You're absorbing everything. Impressive!",
    category: "vocabulary",
    icon: "🧠",
    color: "#047857",
    requirement: JSON.stringify({ type: "vocabulary_learned", count: 50 }),
    influxcoinsReward: 30,
    sortOrder: 31
  },

  // ===== SPEAKING BADGES =====
  {
    slug: "first_dialogue",
    name: "Primeira Conversa",
    nameEn: "First Conversation",
    description: "Ouviu o primeiro diálogo completo com os personagens!",
    descriptionEn: "Listened to the first complete dialogue with characters!",
    ellieMessage: "You listened to your first dialogue! 🎧 Lucas, Emily e Aiko estão felizes em te conhecer. Keep listening!",
    ellieMessageEn: "You listened to your first dialogue! 🎧 Lucas, Emily and Aiko are happy to meet you. Keep listening!",
    category: "speaking",
    icon: "🎧",
    color: "#2563EB",
    requirement: JSON.stringify({ type: "dialogues_listened", count: 1 }),
    influxcoinsReward: 5,
    sortOrder: 40
  },
  {
    slug: "accent_explorer",
    name: "Explorador de Sotaques",
    nameEn: "Accent Explorer",
    description: "Ouviu diálogos nos 3 sotaques: American, British e Australian!",
    descriptionEn: "Listened to dialogues in all 3 accents: American, British and Australian!",
    ellieMessage: "All three accents! 🌍 Agora você conhece como Lucas, Emily e Aiko falam. Each accent has its own charm!",
    ellieMessageEn: "All three accents! 🌍 Now you know how Lucas, Emily and Aiko speak. Each accent has its own charm!",
    category: "speaking",
    icon: "🌍",
    color: "#1D4ED8",
    requirement: JSON.stringify({ type: "accents_heard", count: 3 }),
    influxcoinsReward: 20,
    sortOrder: 41
  },

  // ===== CULTURAL BADGES =====
  {
    slug: "cultural_curious",
    name: "Curioso Cultural",
    nameEn: "Cultural Curious",
    description: "Leu 5 notas culturais sobre USA, UK ou Australia!",
    descriptionEn: "Read 5 cultural notes about USA, UK or Australia!",
    ellieMessage: "Culture matters! 🗺️ Entender a cultura é tão importante quanto aprender a língua. You're doing great!",
    ellieMessageEn: "Culture matters! 🗺️ Understanding culture is as important as learning the language. You're doing great!",
    category: "cultural",
    icon: "🗺️",
    color: "#D97706",
    requirement: JSON.stringify({ type: "cultural_notes_read", count: 5 }),
    influxcoinsReward: 15,
    sortOrder: 50
  },
  {
    slug: "world_traveler",
    name: "Viajante do Mundo",
    nameEn: "World Traveler",
    description: "Explorou diferenças culturais de todos os 3 países!",
    descriptionEn: "Explored cultural differences from all 3 countries!",
    ellieMessage: "You're a world traveler! ✈️ USA, UK e Australia não têm mais segredos para você. The world is your classroom!",
    ellieMessageEn: "You're a world traveler! ✈️ USA, UK and Australia have no more secrets for you. The world is your classroom!",
    category: "cultural",
    icon: "🌏",
    color: "#B45309",
    requirement: JSON.stringify({ type: "countries_explored", count: 3 }),
    influxcoinsReward: 25,
    sortOrder: 51
  },

  // ===== BOOK COMPLETION BADGES =====
  {
    slug: "book1_complete",
    name: "Book 1 Completo",
    nameEn: "Book 1 Complete",
    description: "Completou todos os exercícios extras do Book 1!",
    descriptionEn: "Completed all extra exercises from Book 1!",
    ellieMessage: "Book 1 DONE! 📖 Você completou todos os exercícios do Book 1. That's a huge milestone! On to the next one!",
    ellieMessageEn: "Book 1 DONE! 📖 You completed all exercises from Book 1. That's a huge milestone! On to the next one!",
    category: "book",
    icon: "📖",
    color: "#7C3AED",
    requirement: JSON.stringify({ type: "book_exercises_complete", bookId: 1 }),
    influxcoinsReward: 50,
    sortOrder: 60
  },
  {
    slug: "book2_complete",
    name: "Book 2 Completo",
    nameEn: "Book 2 Complete",
    description: "Completou todos os exercícios extras do Book 2!",
    descriptionEn: "Completed all extra exercises from Book 2!",
    ellieMessage: "Book 2 DONE! 📗 Incrível! Você está evoluindo muito rápido. Your progress is remarkable!",
    ellieMessageEn: "Book 2 DONE! 📗 Incredible! You're evolving so fast. Your progress is remarkable!",
    category: "book",
    icon: "📗",
    color: "#6D28D9",
    requirement: JSON.stringify({ type: "book_exercises_complete", bookId: 2 }),
    influxcoinsReward: 75,
    sortOrder: 61
  },

  // ===== SPECIAL BADGES =====
  {
    slug: "back_to_school_2026",
    name: "Volta às Aulas 2026",
    nameEn: "Back to School 2026",
    description: "Participou da volta às aulas 2026 com o Passaporte Digital!",
    descriptionEn: "Participated in the 2026 back to school with the Digital Passport!",
    ellieMessage: "Welcome back! 🎒 Que bom ter você de volta! 2026 vai ser o seu melhor ano no inglês. Let's make it happen!",
    ellieMessageEn: "Welcome back! 🎒 So glad to have you back! 2026 is going to be your best year in English. Let's make it happen!",
    category: "special",
    icon: "🎒",
    color: "#EC4899",
    requirement: JSON.stringify({ type: "event", event: "back_to_school_2026" }),
    influxcoinsReward: 20,
    sortOrder: 90
  },
  {
    slug: "ellie_friend",
    name: "Amigo da Ellie",
    nameEn: "Ellie's Friend",
    description: "Interagiu com a Ellie 10 vezes!",
    descriptionEn: "Interacted with Ellie 10 times!",
    ellieMessage: "We're friends now! 💜 Adoro conversar com você! You make learning so much fun!",
    ellieMessageEn: "We're friends now! 💜 I love chatting with you! You make learning so much fun!",
    category: "special",
    icon: "💜",
    color: "#A855F7",
    requirement: JSON.stringify({ type: "ellie_interactions", count: 10 }),
    influxcoinsReward: 15,
    sortOrder: 91
  }
];
